# Generated by Django 5.2.7 on 2025-11-05 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='token',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
