# Generated by Django 5.2.7 on 2025-11-06 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
    ]
