# Generated by Django 5.2.7 on 2025-11-19 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0005_detallepedido_pedido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='delivery',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='carrito',
            name='tipo_entrega',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
