# Generated by Django 5.2.7 on 2025-11-20 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0006_carrito_delivery_carrito_tipo_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='direccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='direccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo_entrega',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
