# Generated by Django 5.2.7 on 2025-11-20 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0007_carrito_direccion_pedido_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='tipo_entrega',
            field=models.CharField(blank=True, choices=[('retiro', 'Retiro'), ('delivery', 'Delivery')], default='retiro', max_length=40, null=True),
        ),
    ]
