# Generated by Django 5.2.7 on 2025-11-20 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0008_alter_carrito_tipo_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='delivery',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
