# Generated by Django 5.2.7 on 2025-11-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0009_pedido_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('cancelado', 'Cancelado'), ('completado', 'Completado')], default='pendiente', max_length=20),
        ),
    ]
