# Generated by Django 5.2.7 on 2025-11-02 05:49

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_compra', models.CharField(max_length=100)),
                ('id_sesion', models.CharField(max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=100)),
                ('fecha_transaccion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
