# Generated by Django 5.2.7 on 2025-12-03 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuariopersonalizado_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='telefono',
            field=models.CharField(max_length=15, null=True, verbose_name='Telefono'),
        ),
    ]
